### PR TITLE
REMOVE FEATURE: unnecessary "Courses" page with poor user experience

### LINKED ISSUE #19: Remove unnecessary "Courses" page with poor user experience
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

user

### I can...

avoid being distracted by a poor user experience on the Courses page

### So that...

I can better work with personal schedules

### Discussion

There is currently a menu item in the courses app when logged in called "Courses" which lists the items in the table that stores entries for courses in a personal schedule:

image

When you click on `Courses` you get this:

image

However, this page is really of no value to the end user:
* The `Add New Course` button has been replaced by an `Add` button in the course search results.
* The `Delete` button will be added in another issue ( issue #89 in the proj-courses repo)
* The listing of courses is more useful on the Personal Schedule Details page

So it's time, once the delete button is added on the Personal Schedule Details page, to remove this page.

### Acceptance Criteria

- [ ] The page and route is no longer in `App.js`
- [ ] The page component, stories, and tests are removed, along with any other components (and their stories and tests) that were *only* used on that page.
- [ ] The menu item no longer appears

### Implementation Todos

Frontend:
- [ ] Locate route in app.js
- [ ] Trace through to find page components and other components to remove
- [ ] Remove components, stories and tests
- [ ] Remove item from navigation menu and adjust tests

### PR DESCRIPTION
**Pull request by Frank404NotFound**
Remove "courses" tab to improve UI,
closes #19 

From @pconrad: Merge only after a PR that closes https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/issues/4 is merged.

Update: #4 has become #15 and #32

### CODE REVIEW

**Review by whuang602 — CHANGES_REQUESTED** [review]
Can I get a deployment link? Also, this one cannot be merged until #4 is done and merged

**Comment by Frank404NotFound** [comment]
> Can I get a deployment link? Also, this one cannot be merged until #4 is done and merged

https://proj-frank404notfound-dev.dokku-01.cs.ucsb.edu/

**Comment by pconrad** [comment]
I've added the FIXME-Stalled on this PR since it doesn't seem to be moving forward.  There needs to be forward progress on issue #4  for this to be eligible to be merged for points, and it's not clear that there is any (for example, that issue isn't assigned to anyone on the Kanban board).

**Comment by Frank404NotFound** [comment]
Ruizhe is working on #4  and has decided to refactor it into 3 sub-issues: #15 , #17, #32  because of its design from the past.

**Review by RuizheJiang — DISMISSED** [review]
LGTM

**Pull request closed without merging**
