### PR TITLE
swagger option appears on SHOW_SWAGGER_UI_LINK

### PR DESCRIPTION
**Pull request by miguel-luis9**
FEATURE: Swagger option on navbar #8 

With this PR, the Swagger Link now appears based on SHOW_SWAGGER_UI_LINK value

### CODE REVIEW

**Review by AnikaArora — CHANGES_REQUESTED** [review]
Code looks good, needs a review from your team before I can approve it. Did you test this locally and on Dokku?

**Review by Frank404NotFound — APPROVED** [review]
LGTM

**Review by AnikaArora — APPROVED** [review]
lgtm

**Comment by miguel-luis9** [comment]
Yeah I tested this locally and on dokku. I edited the files after for LM-show-h2console-link branch

**Pull request merged**
